version: '3'

volumes:
  postgres_volume_local:
  postgres_volume_prod:

services:
  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - "local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

  pg-prod:
    image: postgres:14-alpine3.17
    env_file:
      - prod.env
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume_prod:/var/lib/postgresql/data

  migrator_local:
    build:
      context: .
      dockerfile: migration_local.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg_local

  migrator_prod:
    build:
      context: .
      dockerfile: migration_prod.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg_prod

  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis_ch_s